### PR TITLE
add github action for testing

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by dhellmann** [comment]
Some of the tests for patchelf fail when using the container file locally. I'm still working on making it show enough detail to understand which test is failing, to work out why.

**Comment by dhellmann** [comment]
I think if we merge #29 before this, then the changes to the workflow will be tested in this PR.

**Comment by dhellmann** [comment]
@markmc CI is working now.

Each job uses the specified version of Python and runs `test.sh` in a container using `langchain` as the top-level package. The end of the output shows the contents of the test virtualenv.

```
+ pip freeze
aiohttp==3.9.3
aiosignal==1.3.1
annotated-types==0.6.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
dataclasses-json==0.6.4
frozenlist==1.4.1
greenlet==3.0.3
idna==3.6
jsonpatch==1.33
jsonpointer==2.4
langchain==0.1.14
langchain-community==0.0.30
langchain-core==0.1.37
langchain-text-splitters==0.0.1
langsmith==0.1.38
marshmallow==3.21.1
multidict==6.0.5
mypy_extensions==1.0.0
numpy==1.26.4
orjson==3.10.0
packaging==23.2
pydantic==2.6.4
pydantic_core==2.16.3
PyYAML==6.0.1
requests==2.31.0
SQLAlchemy==2.0.29
tenacity==8.2.3
typing_extensions==4.10.0
typing_inspect==0.9.0
urllib3==2.2.1
yarl==1.9.4
```

**Comment by markmc** [comment]
Awesome, thank you!

**Pull request merged**
