### PR TITLE
Fix recursion check

### PR DESCRIPTION
**Pull request by markmc**
Fix recursion check

Firstly to avoid e.g.

```
$ grep 'Successfully built flit_core' work-dir/mirror-sdists-3.9.18.log
Successfully built flit_core-3.9.0-py3-none-any.whl
Successfully built flit_core-3.9.0-py3-none-any.whl
Successfully built flit_core-3.9.0-py3-none-any.whl
Successfully built flit_core-3.9.0-py3-none-any.whl
Successfully built flit_core-3.9.0-py3-none-any.whl
Successfully built flit_core-3.9.0-py3-none-any.whl
```

we want the check based on what the requirement resolves to, which
the sdist name represents.

But secondly, we want to record in-process builds to avoid recursing
into a dependency that we are in the middle of building to deal with
a scenario like this:

```
collect_build_requires A
  -> add_to_build_tracker A
  -> Examine build system dependencies of A
         -> collect_build_requires B
                -> add_to_build_tracker B
                -> Examine build system dependencies of B ... done
                -> Examine build backend dependencies of B ... done
                -> build_wheel B
                -> Examine regular dependencies of B
                       -> collect_build_requires A
                         -> recursion_check A ... skip
         -> add_to_build_order B
  -> Examine build backend dependencies of A ... done
  -> build_wheel A
  -> Examine regular dependencies of A ... done
add_to_build_order A
```

### CODE REVIEW

**Comment by markmc** [comment]
lol, looking into this:

```
collect_build_requires 'poetry-plugin-export<2.0.0,>=1.6.0' /home/markmc/ai-ml/distro/rebuilding-the-wheel/sdists-repo/downloads/poetry_plugin_export-1.7.1.tar.gz ' -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2 -> poetry_plugin_export-1.7.1 -> poetry-1.8.2'
```

**Comment by dhellmann** [comment]
We could track work in progress by adding the sdist base name to a separate list before doing anything with its dependencies. So the first thing `collect_build_requires` would do is check for A's sdist, and if not present add it to the list. Then continue on with the tasks it already does.

```
collect_build_requires A
  -> recursion_check A, maybe return
  -> record_wip A
  ...
```

**Comment by dhellmann** [comment]
I think with that approach we could avoid the repeated checks, too. Just go ahead and recurse one time for every sdist, and let the beginning of `collect_build_requires` prevent additional real work.

**Comment by markmc** [comment]
Nearly there, but this version adds duplicate stuff to build-order.json because the recursion check is in collect_build_requires

**Comment by dhellmann** [comment]
Maybe collect_build_requires should return a value telling the caller if any work was done to add things to the build?

**Comment by markmc** [comment]
> Maybe collect_build_requires should return a value telling the caller if any work was done to add things to the build?

Awkward to do, e.g. the script will just exit with a non-zero a return status

I moved `add_to_build_order` to the end of `collect_build_requires`

**Review by dhellmann — COMMENTED** [review]
This is working for me, let's merge it.

**Pull request merged**
